version: '3.7'
services:
  api:
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        USER_ID: ${USER_ID}
    container_name: currency_rate_test-back
    volumes:
      - ./src/:/opt/currency_rate/src/
      - ./requirements/:/opt/currency_rate/requirements/
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}
    environment:
      - APP_PORT
      - DB_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - DATABASE_URI
    depends_on:
      - db
  db:
    image: postgres:14.5
    container_name: currency_rate_test-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - ${DB_PORT}:5432

volumes:
    postgres_data:

