# Generated by Django 4.2 on 2023-11-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='currencyquote',
            name='currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='quotes.currency'
            ),
        ),
    ]
