# Generated by Django 4.2 on 2023-11-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_currency_alter_currencyquote_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyquote',
            unique_together={('date', 'currency')},
        ),
    ]
